// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.TextSummarizer
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("originalWords")]
        public long OriginalWords { get; set; }

        [JsonProperty("summaryWords")]
        public long SummaryWords { get; set; }

        [JsonProperty("percentDifference")]
        public double PercentDifference { get; set; }

        [JsonProperty("summary")]
        public string Summary { get; set; }
    }
}
